// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMVC_autoDB.Data;

namespace WebMVC_autoDB.Migrations
{
    [DbContext(typeof(WebMVC_autoDBContext))]
    partial class WebMVC_autoDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebMVC_autoDB.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ciekawe fimy o wojnie",
                            Name = "Wojenny"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Śmiechu warte",
                            Name = "Komedia"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Wyciskacz łez i...",
                            Name = "Obyczajowy"
                        });
                });

            modelBuilder.Entity("WebMVC_autoDB.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Film");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Duration = 120,
                            Title = "O jeden most za daleko"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Duration = 160,
                            Title = "Ren"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Duration = 90,
                            Title = "Roman"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Duration = 110,
                            Title = "Shrek"
                        });
                });

            modelBuilder.Entity("WebMVC_autoDB.Models.Film", b =>
                {
                    b.HasOne("WebMVC_autoDB.Models.Category", "MyCategory")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyCategory");
                });

            modelBuilder.Entity("WebMVC_autoDB.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
