// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMVC_G_DBGen.Data;

namespace WebMVC_G_DBGen.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebMVC_G_DBGen.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@example.com",
                            RegDate = new DateTime(2021, 5, 31, 11, 30, 0, 926, DateTimeKind.Local).AddTicks(8538),
                            UserName = "User1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@example.com",
                            RegDate = new DateTime(2021, 5, 31, 11, 30, 0, 926, DateTimeKind.Local).AddTicks(8896),
                            UserName = "User2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@example.com",
                            RegDate = new DateTime(2021, 5, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            UserName = "User3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "user4@example.com",
                            RegDate = new DateTime(2021, 5, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            UserName = "User4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
